export enum ErrorCode {
    // General Errors
    INTERNAL_ERROR = "INTERNAL_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    NOT_FOUND = "NOT_FOUND",
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

    // Auth Errors
    UNAUTHORIZED = "UNAUTHORIZED",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    FORBIDDEN = "FORBIDDEN",
    TOKEN_MISSING = "TOKEN_MISSING",

    // File Errors
    FILE_TOO_LARGE = "FILE_TOO_LARGE",
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
}
