export enum ErrorCode {
    VALIDATION_FAILED = "VALIDATION_FAILED",
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
    FORBIDDEN = "FORBIDDEN",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    EMAIL_REQUIRED = "EMAIL_REQUIRED",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    MISSING_TOKEN = "MISSING_TOKEN",
    NOT_FOUND = "NOT_FOUND",
}
