export enum SuccessCode {
    USER_REGISTERED = "USER_REGISTERED",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    DATA_FETCHED = "DATA_FETCHED",
    CREATED = "CREATED",
    UPDATED = "UPDATED",
    DELETED = "DELETED",
    VALIDATION_SUCCESSFUL = "VALIDATION_SUCCESSFUL",
}
